### PR TITLE
Update links.module.css to be responsive

### PR DESCRIPTION
**Pull request by aburke05**
# Summary of changes
Added responsiveness to the link widget if there are 3 or less items. May need to set a max-height to the image as image gets very large on large screens at 1 item.

## Frontend
links.module.css
- changed hardcode 4 frames to repeat for flexibility with 3 items or less
- may need to set a max-height for image in file as 1 item is quite large on the screen

##Testing
Page to view for testing is: https://deploy-preview-236--ugconthub.netlify.app/admissions-0/.

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
I do think we need different sizing/cropping for only 1 or 2 cards on widescreens:

image

So, not just max-height but a different aspect ratio. Also, smaller images like the UG logo need the opposite treatment to avoid all that blank space.

**Review by tqureshi-uog — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by mmafe** [comment]
If there are only two links, I think whatever decision we go with, they should behave consistently across the front-end.

(Basically, I'm hoping we can avoid basing the front-end styling on configuration occurring on the backend. I know we've done it before, but I'd prefer not to cross the streams if we can help it.)

**Comment by mmafe** [comment]
Hi @aburke05 and @tqureshi-uog, in theory we could create another class that would be conditionally applied if there are only 2 or less link elements. However, looking at the result, I prefer the look when it's using the full space (as opposed to forcing it to use only 2 blocks worth). People would have to ensure their images are large enough, but it feels more intuitive.

I've put some comparison shots below. Let me know your thoughts on just proceeding with this fix as is (as opposed to changing it to be applied conditionally).

# Using full space

image

image

# Forcing it to use 4 column sizing when less than 3

image

image

**Review by mmafe — APPROVED** [review]
I think this looks good.

**Comment by mmafe** [comment]
Note: If we did want to use 4-column width for two or less items, we could do the following:

Add a .outer div.inner.twoOrLess class to the links.module.css stylesheet:
```
@media (min-width: 768px) {
  .outer div.inner {
    grid-template-columns: repeat(auto-fit, minmax(20%, 1fr));
  }
  .outer div.inner.twoOrLess {
    grid-template-columns: 1fr 1fr 1fr 1fr;
  }
}
```

Add a numColumns variable and add it conditionally to the LinksInner element in links.js:

```
function Links({ links = [], title, headingLevel, description }) {
  const isGrid = links?.some((item) => item.image);
  const Heading = getHeadingLevel(headingLevel);
  const numColumns = links.length;
  // const LinkHeading = title ? getHeadingLevel(headingLevel, 1) : "p";
  const LinksInner = isGrid ? "div" : "ul";

  return (
    <div className={styles.outer}>
      {title && <Heading>{title}</Heading>}
      {description && <p>{description}</p>}

      <LinksInner className={`${styles.inner} ${(numColumns < 3) && styles.twoOrLess}`}>
        {links.map((link) => {
          const { id, title, url, image } = link;

          return isGrid ? (
            <GridLink key={id} title={title} url={url} image={image} />
          ) : (
            <ListLink key={id} title={title} url={url} />
          );
        })}
      </LinksInner>
    </div>
  );
}
```

**Comment by mmafe** [comment]
Added the above changes to a separate branch link-widget-responsive-optionb

**Comment by mmafe** [comment]
We received confirmation from C&M that we should go with the full-width option for two elements. I think we can proceed with this PR as is then.

**Review by tqureshi-uog — APPROVED** [review]
Approved, but it needs to be made clear to users that if they anticipate fewer than 4 images, they need to ensure the images they upload look good at a large size as well (as opposed to how the smaller UG logo appears in the screenshots above).

**Pull request merged**
