### PR TITLE
Refactor Media and Text, Section, and Button widgets

### PR DESCRIPTION
**Pull request by tqureshi-uog**
# Summary of changes
U of G media player removed due to accessibility issues, replaced with the default players for YouTube and Vimeo. Section widget refactored to use Bootstrap 5 layout classes instead of a custom grid. Media and Text widget refactored to offer more layout options when it's in a section. Button widget also refactored to use Bootstrap 5 classes instead of custom code.

## Frontend
- U of G media player removed from `video.js`
- `sectionWidgets.js` refactored to:
    - sort widgets into primary and secondary columns
    - only permit General Text, Media and Text, and Buttons in the secondary column (i.e. right sidebar)
    - use Bootstrap 5 classes
    - remove `contentExists` function
- `mediaText.js` refactored to: 
    - let videos also use the `size` field to determine layout
    - use Bootstrap 5 classes
    - remove `contentExists` function
- `sectionButtons.js` refactored to use Bootstrap 5 classes and remove `contentExists` function
- `button.js` refactored to use Bootstrap 5 classes, avoid rendering an empty `<i>` tag, and remove `contentExists` function
- `ConditionalWrapper` function added to `ug-utils.js`
- `fontAwesomeIconColour` function in `ug-utils.js` updated to return correct class names from the U of G stylesheet
- References to `ctaPara.js` removed since this widget is no longer available in the Drupal backend
- `gatsby-node.js` updated with new schema for `Special Regions` taxonomy
- General code refactoring to use [Optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) wherever possible

## Backend
- `Section Column` taxonomy revised to remove `cta` option. The `right` option is now called `Secondary` while `main` is `Primary` and `left` has been labeled as discontinued
- `Image Size` field label in Media and Text paragraph type changed to `Media Display Size` and instructions updated accordingly
- `Section Column` instructions updated for Media and Text as well as Button widget
- `Manage form display` settings for all paragraph fields switched from `Paragraph Legacy` to `Paragraphs (stable)` thus offering far more flexibility to content editors (e.g. the ability to duplicate a widget and expand or collapse all widgets at once)
- `Manage form display` setting for `Button Section` in Media and Text widget changed so that `Default paragraph type` is set to `None` (meaning content editors will only see an `Add Buttons Section` button instead of all button widget fields open and expanded)
- New taxonomy vocabulary `Special Regions` added to `Buttons Sections` choices for `Section Column` in order to offer the Call to Action display method
- [Menu Admin per Menu](https://www.drupal.org/project/menu_admin_per_menu) module added (to be enabled and configured later)
- Security update drupal/core to 9.3.12

# Test Plan

Gatsby Cloud site: https://tqtest.gatsbyjs.io
Drupal multidev: https://secfix-chug.pantheonsite.io/

- https://tqtest.gatsbyjs.io/about should show first two videos side by side with text underneath and The Cannon video at full width 
- https://tqtest.gatsbyjs.io/chancellor/selection-committee should show images roughly 1/3 the size of their accompanying text blocks. These images are set to "Small" and not in a section
- https://tqtest.gatsbyjs.io/choose-u-of-g should show `Apply to U of G` and `Tour U of G` images side by side with text and buttons underneath. Buttons in the right column should all be the same width
- https://tqtest.gatsbyjs.io/grce/contact should show images and text side-by-side with two images per row
- https://tqtest.gatsbyjs.io/land-acknowledgement should show video at full width of main column
- https://tqtest.gatsbyjs.io/studentexperience/advising-and-support should have 3 images in a row with the text underneath
- https://tqtest.gatsbyjs.io/studentexperience/get-involved should show buttons beneath the images
- https://tqtest.gatsbyjs.io/welcome-home should show two videos side by side. Further down the page in the "Resources" section, the buttons should be of variable width and in a row on large screens but equal width and stacked on small screens. The last button on the page should have the Call to Action style (red in colour, larger text, centered)
- See https://tqtest.gatsbyjs.io/media-text-test for a demo of various image layout options

**Note:** You can also test the above and other pages via the Pull Request build at https://build-bbe14b59-a567-449b-aef8-3f13863b1174.gtsb.io/

## Known Issues
- Some spacing and alignment might be slightly off in places. Most instances can be resolved by rearranging widgets in the backend (e.g. instead of having two separate sections, combine their content into one)
- The `Section Column` taxonomy will need to be manually updated on the live site to reflect changes on the secfix multidev
- The new `Special Regions` taxonomy will need to have terms added manually

### CODE REVIEW

**Comment by abanuog** [comment]
Added a test page with  profiles and a sidebar. The  profile text alignment is off a bit: https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/profile-section

**Comment by tqureshi-uog** [comment]
> Added a test page with profiles and a sidebar. The profile text alignment is off a bit: https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/profile-section

The issue here is how one chooses to add the heading. If you put the heading within the ckeditor text area, you need to add the class `mt-md-0` in order to override the default top margin. But if you use the Media and Text widget's **Title** field instead, the class will be added automatically. See https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/grce/contact for reference (on the backend the page is https://secfix-chug.pantheonsite.io/node/777/edit?destination=/admin/content)

**Comment by abanuog** [comment]
> > Added a test page with profiles and a sidebar. The profile text alignment is off a bit: https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/profile-section
> 
> The issue here is how one chooses to add the heading. If you put the heading within the ckeditor text area, you need to add the class `mt-md-0` in order to override the default top margin. But if you use the Media and Text widget's **Title** field instead, the class will be added automatically. See https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/grce/contact for reference (on the backend the page is https://secfix-chug.pantheonsite.io/node/777/edit?destination=/admin/content)

It's not so much about the heading, but about the profile fields (eg. email) going over into the other profile beside it. When you start resizing the screen, it is even more noticeable.

**Comment by snschau** [comment]
> > > Added a test page with profiles and a sidebar. The profile text alignment is off a bit: https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/profile-section
> > 
> > 
> > The issue here is how one chooses to add the heading. If you put the heading within the ckeditor text area, you need to add the class `mt-md-0` in order to override the default top margin. But if you use the Media and Text widget's **Title** field instead, the class will be added automatically. See https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/grce/contact for reference (on the backend the page is https://secfix-chug.pantheonsite.io/node/777/edit?destination=/admin/content)
> 
> It's not so much about the heading, but about the profile fields (eg. email) going over into the other profile beside it. When you start resizing the screen, it is even more noticeable.

Was playing with this a bit - https://build-e4cbe864-1b86-45f9-af8a-ed07fbf27e5f.gtsb.io/profile-section  the alignment issues is more to do with the data entered. I tried a section with smaller images and it looks better. Also, I added the class mt-md-0 to the header for the secondary column.  There are still some minor alignment issues - it does not quite line up with the top of the primary column.  But, not sure that is a large issue.

**Comment by snschau** [comment]
For the back end - the selection of primary or secondary on the widgets - should it be in the same location - I.e. under the title/class fields, but before the data fields - such as it is for media and text widget, general text widget has it below the content field?

**Review by snschau — APPROVED** [review]
I am not seeing anything that would prevent this from being merged.

**Comment by abanuog** [comment]
> > > > Added a test page with profiles and a sidebar. The profile text alignment is off a bit: https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/profile-section
> > > 
> > > 
> > > The issue here is how one chooses to add the heading. If you put the heading within the ckeditor text area, you need to add the class `mt-md-0` in order to override the default top margin. But if you use the Media and Text widget's **Title** field instead, the class will be added automatically. See https://build-b6d54f00-a7f2-494e-87cb-000b7f73b014.gtsb.io/grce/contact for reference (on the backend the page is https://secfix-chug.pantheonsite.io/node/777/edit?destination=/admin/content)
> > 
> > 
> > It's not so much about the heading, but about the profile fields (eg. email) going over into the other profile beside it. When you start resizing the screen, it is even more noticeable.
> 
> Was playing with this a bit - https://build-e4cbe864-1b86-45f9-af8a-ed07fbf27e5f.gtsb.io/profile-section the alignment issues is more to do with the data entered. I tried a section with smaller images and it looks better. Also, I added the class mt-md-0 to the header for the secondary column. There are still some minor alignment issues - it does not quite line up with the top of the primary column. But, not sure that is a large issue. Edit: it might be it lines up with the top of the images, but the names are just a bit lower.

It looks like it's related to the image size choice, not the text data. I guess we can tell users to only use the small option in this case.

**Comment by tqureshi-uog** [comment]
> It looks like it's related to the image size choice, not the text data. I guess we can tell users to only use the small option in this case.

No, it works for size choice "Medium" as well - see https://tqtest.gatsbyjs.io/media-text-test

What the Bootstrap 5 class `mt-md-0` does is remove the top margin on the Media and Text title field when the text block appears next to the image (as opposed to underneath). When the Media and Text widget is in a section and Media Display Size is set to either "Small" or "Medium", the  `mt-md-0` class is automatically applied. Also see the additions to https://tqtest.gatsbyjs.io/profile-section

As for the issue with text (e.g. long email addresses or names) overflowing, that's been resolved by adding the `text-break` class to the Media and Text widget's text block.

**Review by mmafe — APPROVED** [review]

**Comment by abanuog** [comment]
> > It looks like it's related to the image size choice, not the text data. I guess we can tell users to only use the small option in this case.
> 
> No, it works for size choice "Medium" as well - see https://tqtest.gatsbyjs.io/media-text-test
> 
> What the Bootstrap 5 class `mt-md-0` does is remove the top margin on the Media and Text title field when the text block appears next to the image (as opposed to underneath). When the Media and Text widget is in a section and Media Display Size is set to either "Small" or "Medium", the `mt-md-0` class is automatically applied. Also see the additions to https://tqtest.gatsbyjs.io/profile-section
> 
> As for the issue with text (e.g. long email addresses or names) overflowing, that's been resolved by adding the `text-break` class to the Media and Text widget's text block.

What I was saying was that on a page with a sidebar (https://tqtest.gatsbyjs.io/profile-section), when you use small images with profiles, the text looks better than if you use medium images.

**Pull request merged**
