### PR TITLE
Menus

### PR DESCRIPTION
**Pull request by snschau**
# Summary of changes
Check if page has a taxonomy that includes menu_name (menu_machine_name)
If this taxonomy has been added to the page, use that menu as the one to include on the page. This is to counter when page has been added to multiple menus. 

Note: Could not find a way to use the menu that was selected on the page in drupal using show in menu. 

## Frontend
Change in page.js 
 - added to query to get the taxonomy primary navigation - field_menu_machine_name
 - if the primary navigation exists use field_menu_machine_name instead of the default of the menu_name from the menu table. 

For user documentation need to add to the create/edit basic page part - to add a menu to the page add your Menu to the Primary Navigation field. 

[X] My changes are accessible (at minimum WCAG 2.0 Level AA)
[X] My changes are responsive and appear as expected on mobile and desktop views.
[X] After merging, I will update the [Content Hub documentation](https://uoguelphca.sharepoint.com/sites/UniversityContentHubInformationGroup) and ensure the Content Hub trainer understands how my changes will affect users.

## Backend
List all significant changes to the Drupal site (e.g. new fields, content types, modules, etc). If adding new fields, try to include help text to ensure users understand how to use the fields.

Multidev https://sns-menu-chug.pantheonsite.io/

Added Taxonomy Term
 - Primary Navigation 
 - added field_menu_machine_name to this term 
 - Note: This term is to be created when a menu is added by administrators, so that the correct machine name is entered.
 
Added reference to Primary Navigation taxonomy to Basic Page.
 - Help text {Select the Primary Navigation for this page (this will determine what Menu is displayed on the Page)}

For users 
# Test Plan

Do a local build using this branch and the listed multidev.

Any existing page that is linked to a menu via the provide a menu for the page , should still show the menu for that page (the Taxonomy (Primary Navigation) has not been set. Thus, the existing method still works. 

For when the Taxonomy (Primary Navigation) is set. Check that the ovc manu is listed on the following pages:

http://localhost:8000/test-menu-page-menu-added/ - shows that if both the Taxonomy (Primary Navigation)  is set to the same menu that is set on provide a menu for the page - the correct menu is displayed (Uses the Taxonomy item as default)

http://localhost:8000/test-menu-page-different-menu-added/ - shows when the Taxonomy (Primary Navigation) is set to a different menu that is set on provide a menu for the page - the Primary Navigation takes priority. However the link will still show on the other menu - http://localhost:8000/experiential-learning/about-us/about-experiential-learning/

http://localhost:8000/test-menu-page-no-menu-added/ - shows when no menu was set on provide a menu for the page. However, the Taxonomy (Primary Navigation) was set - OVC menu should show.

### CODE REVIEW

**Comment by snschau** [comment]
Merged main into branch to resolve conflicts

**Review by anduonguog — DISMISSED** [review]

**Comment by ljairath** [comment]
Hi Scott. Looking good ... just a couple of comments.

1. Is there a typo for the help text. See the image.
2. I am not sure if I understand this comment "Merged main into branch to resolve conflicts".  

Thank you for showing An and I the code/process.
Screenshot 2024-03-19 at 4 51 39 PM

**Review by ljairath — COMMENTED** [review]
Hi Scott. It looks good ... just a couple of comments.

1. Is there a typo for the help text. See the image.
2. I am not sure if I understand this comment from above "Merged main into branch to resolve conflicts".

Thank you for showing An and I the code/process.

Screenshot 2024-03-19 at 4 51 39 PM

**Comment by ljairath** [comment]
Sorry. I closed the pull request by mistake. Reopening.

**Comment by snschau** [comment]
Lalit - There was a problem reported by git that this menus branch had some conflicts and was unable to merge. So, I merged the main branch into this branch to resolve those conflicts so that this branch can be then merged into main.

I have removed the Help Text from the help text field.

**Review by anduonguog — COMMENTED** [review]
looks good!

**Review by ljairath — APPROVED** [review]
Scott, it's looking good.

**Review by anduonguog — APPROVED** [review]

**Review by mmafe — APPROVED** [review]
Works.

**Pull request merged**
