### PR TITLE
add outline for 1 of 2 buttons

### PR DESCRIPTION
**Pull request by anduonguog**
# Summary of changes
Change the layout of the buttons (on the Bachelor of Commerce) from being 2 solid red buttons stacked to one outlined button on the left and one solid red button on the right. Also make "Learn More: all uppercase to match the "APPLY NOW" button.

## Frontend
List all significant changes to Gatsby code:
program-page.js, added code below:
btnClass = {index === (callToActionData.length - 1) ? 'btn-primary':'btn-outline-primary'}
callToAction.js, added line below:
let className = classNames(btnClass,'btn fs-1 me-4 p-4 w-100');

# Test Plan

Check if the Apply Now button change to an outlined button:
https://deploy-preview-274--ugconthub.netlify.app/programs/bachelor-of-commerce/

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
Are the buttons supposed to appear side by side in desktop view?

> Change the layout of the buttons (on the Bachelor of Commerce) from being 2 solid red buttons stacked to **one outlined button on the left and one solid red button on the right.**

If so, they still display as stacked:

image

If the side-by-side display is no longer required, this PR should be good to merge, but if they do still want it, the classes would need to be adjusted.

**Comment by anduonguog** [comment]
updated to make the buttons align side by side(left and right) on bigger screen, on smaller screen(mobile and tablet) top on each other.

**Comment by mmafe** [comment]
Hi @anduonguog , I think the update is making a single button appear off-centre. See https://deploy-preview-274--ugconthub.netlify.app/programs/bachelor-of-science/

image

**Review by mmafe — CHANGES_REQUESTED** [review]
Buttons are not appearing properly when a single button is on a page. (Is there a way we can just use the existing Button component? It seems to have call to actions built in already.)

https://preview-ugconthub.netlify.app/widget-examples/#buttons

**Review by mmafe — APPROVED** [review]
Updates work! Thank you

**Review by tqureshi-uog — APPROVED** [review]

**Pull request merged**
