### PR TITLE
Add new top navigation to Content Hub pages

### PR DESCRIPTION
**Pull request by tqureshi-uog**
# Summary of changes
Add the new UG top navigation and associated web components to the Content Hub. Also remove the default submenu from pages and programs not assigned to an existing menu.

## Frontend
- Update `gatsby-ssr.js` with links to new web components and styles
- Update `headerMenu.js` to use new sub-navigation logic and structure
- Remove references to old `main` menu from `index.js`, `page.js` and `program-page.js`

### Incidental Changes
- Upgrade packages
- Remove jQuery (no longer needed)
- Increase timeout value for `gatsby-source-drupal` to prevent failed local builds
- Reduce WordPress content pulled in Dev environment to avoid timeout errors

## Backend
N/A

# Test Plan
- View https://chugtest.gatsbyjs.io/ and confirm the new Top Navigation appears and works as expected. No submenu should be on the page.
- Go to https://chugtest.gatsbyjs.io/studentexperience/ and confirm dropdown menu items work as expected. Also confirm the Modal Video works as expected.
- Go to https://chugtest.gatsbyjs.io/pathobiology/people/faculty/andrew-kropinski/ and confirm OVC's menu works as expected
- Go to https://chugtest.gatsbyjs.io/grce/ and confirm "GRCE" shows and works as this site's home link.
- Go to program https://chugtest.gatsbyjs.io/programs/bachelor-of-arts-general-fully-online/ and confirm no submenu appears
- Go to major page https://chugtest.gatsbyjs.io/programs/biomedical-engineering/ and confirm no submenu appears

# Known Issues
- Some units use the word "Home" for their top navigation link. This will need to be updated to a proper site name for better UX and information architecture.
- Sites with long menu titles look bad at the 1024px width breakpoint: 
image

### CODE REVIEW

**Comment by mmafe** [comment]
Still mid-review, but so far, have noticed the modal video title and close button get obscured by the grey menu bar in all browsers when the viewport is shorter than 800px.

image

**Comment by mmafe** [comment]
(Another known/out of scope observation) When looking at the landmarks for the page, I'm noticing it's a banner landmark, but there's no nav landmark for the navigation menus. It's out of scope for this PR, so I've created an issue over on the web-components repo: https://github.com/ccswbs/web-components/issues/2

**Comment by mmafe** [comment]
**Observation without an action item:** When I'm on one of the program/major pages, I wish the Academics section in the global menu was highlighted yellow. This may not be something we can fix now, but there is a sense of "I don't know exactly where I am" for pages that are not in a menu, such as a the programs.

image

**Review by mmafe — COMMENTED** [review]
Code appears to work as expected. Any issues that I've found are related to the top nav web-component or the modal video component (and therefore are beyond the scope of this PR).

I'm holding off on approval until we've confirmed that top nav is ready for release. (But in theory, I have approved this PR.)

**Comment by RazaMM** [comment]
Yeah looks like we may need to make some changes to the top nav itself before we go ahead and merge this. I think the modal issue actually may be a problem with the top nav having too high of a z-index. Regardless I'll update the top nav tomorrow to address these issues.

**Pull request merged**
