### PR TITLE
Upgrade to Gatsby 5

### PR DESCRIPTION
**Pull request by tqureshi-uog**
# Summary of changes
Upgrade to Gatsby 5

## Frontend
- Update `package.json` and `package-lock.json` to use latest versions of Gatsby, React, and assorted packages/plugins
- Delete `.nvmrc` file to remove forced use of Node v16 (Gatsby 5 requires v18)
- Run [Gatsby-provided codemod](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#graphql-schema-changes-to-sort-and-aggregation-fields) to update GraphQL queries where needed
- Remove unused `gatsby-background-image` plugin to resolve npm errors

### Incidental changes
- Clean up `gatsby-config.js` by removing duplicate entries and rearranging others (all the plugins with no additional settings are in alpha order in a section followed by those *with* additional settings, also in alpha order)

## Backend
N/A

# Test Plan

## Local
- Clone this repository into a *new* directory (e.g. `gus2` or whatever other name you wish to use)
- Upgrade to Node v18 ([nvm](https://github.com/nvm-sh/nvm) can help with this)
- Checkout the `gatsby5` branch
- ~Run `npm install --legacy-peer-deps` (if your own version of npm is 7 or higher - if not, you can skip the `--legacy-peer-deps` flag)~ After removing  `gatsby-background-image` it's no longer necessary to use `legacy-peer-deps` - you can now use `npm install` regardless of your npm version
- Run `gatsby develop --verbose`
- Test http://localhost:8000/ and various pages/programs
- Go to http://localhost:8000/___graphql and experiment with the new GraphQL interface (many new features added and a dark mode is available as well)

## Gatsby Cloud
- Go to https://ugconthub-gatsby5.gatsbyjs.io/ and test various pages and programs. High-profile pages are recommended, e.g. Student Experience, the President's Office, Future Students, Lang, etc.
- Go to https://tqtest.gatsbyjs.io/ and test various unpublished pages and programs

## Known issues
- If building locally, you'll see console warnings about `StaticQuery` being deprecated. This does not impact functionality at the moment, but we will need to switch to `useStaticQuery` to resolve it.

### CODE REVIEW

**Comment by mmafe** [comment]
Is there a way to do the nom install without the --legacy-peer-deps flag? It's not a recommended flag [as per npm docs](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps), so if we are upgrading to Gatsby 5, I'd prefer if we could do it without that.

**Comment by tqureshi-uog** [comment]
> Is there a way to do the npm install without the --legacy-peer-deps flag? It's not a recommended flag [as per npm docs](https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps), so if we are upgrading to Gatsby 5, I'd prefer if we could do it without that.

We have zero choice in the matter if using, locally, a version of npm higher than 7 - Gatsby themselves recommend it: https://learn.microsoft.com/en-us/windows/wsl/compare-versions

So if your own version of npm is lower than 7, you could skip the `--legacy-peer-deps` flag. On Gatsby Cloud, they use npm v6.14.17

**Comment by mmafe** [comment]
Runs locally for me!

**Review by mmafe — APPROVED** [review]
Works for me locally. Does not appear to break the world. In terms of timing for the merge, I'll leave that up to those who are present during the rest of December. 👍

**Review by snschau — APPROVED** [review]

**Pull request merged**
