### PR TITLE
Image Overlay Component

### PR DESCRIPTION
**Pull request by mmafe**
# Summary of changes
- Add image overlay component with 5 options:
  - Dark Overlay
  - Light Overlay
  - Red Background
  - Blue Background
  - Yellow Background
- Allowed the image overlay to include General Text, Quote, Modal Video and Section Buttons
- Image Overlay appears full-width unless added to a Section

## Frontend
- Add Image Overlay component 
- Add Quote component
- Make img-dark a little bit darker

## Backend
Multisite: [https://textbg-chug.pantheonsite.io](https://textbg-chug.pantheonsite.io)
- Add Image Overlay paragraph type
- Renamed Story:Video Button and Story:Quote to just "Modal Video Button" and "Quote" paragraph types

# Test Plan

- After compiling, open /image-overlay-example (e.g. https://build-ac5a58c9-3e4b-43c3-8c40-5523edd6d7c1.gtsb.io/image-overlay-example)
- On the textbg multisite, attempt to add different types of Image Overlays
- Look for bugs, oddities and anything that behaves or appears in an unexpected manner

### CODE REVIEW

**Review by tqureshi-uog — CHANGES_REQUESTED** [review]
On the backend, the "Content" field for the Image Overlay widget should be required to prevent users from saving a completely empty widget which in turn renders as a series of empty divs (see https://mmtest.gatsbyjs.io/image-overlay-break and inspect the code)

Also, an odd hover effect appears on inline link text - it's white (again see https://mmtest.gatsbyjs.io/image-overlay-break)

**Comment by mmafe** [comment]
Updated backend to add help text for quote and make Image Overlay content field required.
Updated frontend to check Image Overlay for content before rendering and fix image overlay link style issue.

**Comment by tqureshi-uog** [comment]
On https://build-53717101-58d5-49d9-b4e4-de0ea576c2c0.gtsb.io/image-overlay-break the link text no longer turns white on hover/focus, but it doesn't have the blue background either - only the underline disappears.

**Comment by mmafe** [comment]
@tqureshi-uog Background on link colour fixed

**Review by tqureshi-uog — APPROVED** [review]

**Comment by abanuog** [comment]
I added an overlay without a background, and the link shows with a white underline. Is that expected ?
Also, these are just a couple of design related items, maybe check with Linda:

- With the red background, the red button doesn't stand out enough
- With the blue background, the yellow quotes look very bright

**Comment by mmafe** [comment]
@abanuog Refactored the code so if no image is selected (and no Red, Yellow or Blue backgrounds are chosen), it displays content as you'd typically see it in .page-container .site-content. If the user has selected Dark Overlay/No Image, it'll use bg-dark. If the user has selected No display style/No Image OR Light Overlay/No Image, it'll use bg-light.

For the design-related items, I'll check in with Linda.

I was also going to update the code so the btn-outline classes wouldn't get lost...and then I realised, maybe we should just leave it because Bootstrap says in their documentation: "Some of the button styles use a relatively light foreground color, and should only be used on a dark background in order to have sufficient contrast." And I thought...maybe it's up to the user not to use certain buttons in certain scenarios.

Either way, will check in with you tomorrow to take a look at what I've done. :)

**Comment by abanuog** [comment]
The only thing I noticed is the disappearing button issue with the solid backgrounds, but you explained it in the text. I think
this can be merged.

**Review by abanuog — APPROVED** [review]

**Pull request merged**
