### PR TITLE
Leftrightimage

### PR DESCRIPTION
**Pull request by snschau**
# Summary of changes
Added an option in Media Text Widget to display images on the right of the text block. Left the default (or no choice) to the image displayed on the left.

## Frontend
gatsby-node.js
 - added field_media_image_side to schema for paragraph__media_text type
 
mediaText.js
 - added field_media_image_side to the query.
 - added code to check if field_media_image_side data exists (default to 'Left' if does not) and assign it to a variable.
 - refactored code to check what side the image is to appear on and to render it either on the left or right.  Side choice will be ignored if a Video is the media item. 

## Backend
Multidev: https://imagealign-chug.pantheonsite.io/
**(Note: new mulitdev)**

In the Paragraph type: Media and Text added the field Image Side (Image only) - field_media_image_side. Defaults to Left for new items, but existing content with no value will still show on the left if is an image. Not a required field, so when updating existing pages users are not required to change it. But all new content will have a value. 

Help text : For images only: Choose the side of the text it will appear on. Note: this will only work when images are displayed beside the text. Also, if selected and content is stacked the image will appear below the text. 

Left - image on the left text on the right 
Right - text on the left and image on the right

# Test Plan

https://sstest.gatsbyjs.io/ is configured to build on this branch and usehttps://imagealign-chug.pantheonsite.io/ as the data source. When testing rebuild SS Test on gatsby cloud or on a local build.

Add a new page and add Media and Text widgets and select Left or Right, add a video to check if this setting is ignored. 
Check any existing page that has Media and Text widgets and ensure they are displaying as they should. 

https://sstest.gatsbyjs.io/learn/ shows how it will look with alternating left and right images. 

https://imagealign-chug.pantheonsite.io/node/876/edit?destination=/admin/content%3Ftitle%3Dlearn%26uid%3D%26type%3DAll%26status%3DAll%26field_tags_target_id_op%3Dor%26field_tags_target_id%3D%26items_per_page%3D50

[Widget Examples](https://sstest.gatsbyjs.io/widget-examples/) 
[Media and Text Examples](https://sstest.gatsbyjs.io/media-and-text-examples/)

Both work as expected (with some elements unchanged) note in the section with right columns - I have made the item to have the image on the right, to show that it works in this case).

I will be a way next week - feel free to make any changes need to approve this PR and publish it. Or make comments and I will deal with them when I get back.

### CODE REVIEW

**Comment by snschau** [comment]
Just a note - Miranda suggested a name change to Image Alignment instead of Image Side

**Comment by snschau** [comment]
> Just a note - Miranda suggested a name change to Image Alignment instead of Image Side

I have changed the display name to Image Alignment. Should I change the field name and  thus the code as well?

**Comment by tqureshi-uog** [comment]
On the new multidev, recommend making the keys all lowercase in https://imagealign-chug.pantheonsite.io/admin/structure/paragraphs_type/media_text/fields/paragraph.media_text.field_media_image_alignment/storage (labels can stay as they are)

You should still be able to change them despite the "field settings can no longer be changed" message. Keys should always be as simple as possible to avoid potential confusion and typos and also for consistency with other field settings, e.g. 
image

**Comment by abanuog** [comment]
Seems to work as expected.

**Review by abanuog — APPROVED** [review]

**Review by mmafe — CHANGES_REQUESTED** [review]
In mobile view, the images appear below the description. Is there  a remedy for this?

**Comment by tqureshi-uog** [comment]
> In mobile view, the images appear below the description for the alternated item. Is there a remedy for this?

There is, but it will require rethinking and refactoring the conditional statement. Right now, the logic is such that the image renders *below* the description if image alignment is set to "right." Instead, the image should always render above the description and its left/right alignment should be controlled by CSS classes conditionally applied (this would be a better, more robust approach anyway)

**Review by tqureshi-uog — CHANGES_REQUESTED** [review]

**Comment by mmafe** [comment]
@snschau Could you close this PR if it's being replaced by a different one?

**Pull request closed without merging**
