### PR TITLE
Redirects

### PR DESCRIPTION
**Pull request by mmafe**
# Summary of changes
- Installed gatsby-plugin-client-side-redirect
- Created redirect on Gatsby (client side) using Drupal redirects

## Frontend
- Redirects should now exist (based on Drupal redirects)

## Backend
**Multidev:** [https://redirects-chug.pantheonsite.io](https://redirects-chug.pantheonsite.io)
- Enabled Redirect module and Redirect 404 module
- Allow Publishers, Gatsby Build and Gatsby Preview to administer individual redirects
- Unauthenticated users do not have access to redirect JSON data

# Test Plan
Note: If you are testing locally, you will need to run `gatsby build` rather than `gatsby develop`, then navigate to the public folder to find the page with the client-side redirect on it. Alternatively, you can test via Gatsby Cloud.

- Visit [https://build-59002b1c-66be-4309-be74-990a12d8c831.gtsb.io/testing-redirects](https://build-59002b1c-66be-4309-be74-990a12d8c831.gtsb.io/testing-redirects) which should redirect to another page
- Go to [https://redirects-chug.pantheonsite.io](https://redirects-chug.pantheonsite.io)
- Add a new basic page or program
- Either compile locally or use Gatsby Cloud (connecting your site to the redirects branch using the redirects-chug.pantheonsite.io) to create a new build 
- View the page you created on the compiled build (copy the URL)
- Back on Drupal, change the name of the page or program (this should create a new redirect)
- Compile again locally (run gatsby build instead of Gatsby develop if running things locally) or trigger a new build on your connected Gatsby Cloud site
- Once the build is done, go back to the URL you copied. It should redirect to the updated URL.
- If compiling locally, go into the public directory that was generated by gatsby build and navigate to the page you previously created (a.k.a. same URL as the page you copied). It should have a client-side redirect on the page.

# Caveat
I believe this will only work for Content Hub pages that are already available via the gateway. (So if there's a blanket rule where all pages under /my-department/ are available, then if you change the name of /my-department/my-page, it will redirect to the new page as long as it also lives under /my-department/)

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
Looks like some conflicts have developed as a result of updates to `master` since this PR was opened. Try merging the latest changes (on your multidev as well if possible)

**Review by tqureshi-uog — CHANGES_REQUESTED** [review]
Due to updates to master since you created this PR, conflicts exist. I'd recommend resolving them (as well as updating your multidev with the latest Drupal master changes) and then we can finish reviewing this. At first glance, there don't appear to be any changes that would disrupt or interfere with other things.

**Comment by mmafe** [comment]
- Merged in the master branch
- Recreated the multidev at [https://redirects-chug.pantheonsite.io](https://redirects-chug.pantheonsite.io)
- Once the multidev is merged, the automatic checks against UG Content Hub should start working

**Comment by tqureshi-uog** [comment]
It doesn't seem to work for me. On the redirects Drupal site, I changed the URL for an existing page - https://tqtest.gatsbyjs.io/studentexperience/indigenous-undergraduate-research-assistantships to https://tqtest.gatsbyjs.io/studentexperience/iura - but when I go to https://tqtest.gatsbyjs.io/studentexperience/indigenous-undergraduate-research-assistantships I get the Gatsby "Not Found" page. I've tried doing a cache clear and manual rebuild and opening in an incognito window, but it makes no difference. As far as I can tell, the redirect should be in place:

image

**Review by tqureshi-uog — APPROVED** [review]
Removing slugify seems to have done the trick - https://tqtest.gatsbyjs.io/studentexperience/indigenous-undergraduate-research-assistantships now successfully redirects to https://tqtest.gatsbyjs.io/studentexperience/iura

**Pull request merged**
