### PR TITLE
Add Yaml block for creating custom content on the Gatsby side

### PR DESCRIPTION
**Pull request by mmafe**
# Summary of changes
When pages require functionality that does not exist yet in our components library, we can use a YAML block to render the component in the middle of Basic Page content. (Later, if more people need the new component and the requirements are set, we can build an actual Drupal widget for it.)

## What is the benefit?
- This is best suited for custom pages that need to be developed quickly and/or do not have their requirements firmly set.
- Custom pages (like Impact Report) can now be created as Basic Pages (therefore they will have a Drupal node ID, alias, a place in the menu, redirects eventually, etc.

## How do I store the Yaml data for the block?
- **Option 1:** Store it in the Drupal Yaml block itself under Yaml Mapping.
      - _Pro:_ Feeds into the idea of content stored on Drupal.
      - _Con:_ Blocks do not have revisions in D9 yet :scream:...but eventually, if they do, users can edit the blocks.
- **Option 2:** Store it on  the Gatsby side at /src/data/block and query from it from there. You would still need a Yaml block to place the component in a Basic Page. The benefit to this is we have version control. For example, I was a little nervous someone would delete the mappings I created for International, so I saved them in /src/data/block just in case. (I'm not querying them, but I could if I wanted to, using the same query style as Impact Report)

## Frontend
- Updated schema for Yaml Widget and Yaml Blocks; added modal video to basic page
- Added Yaml Widget component
    - Maps the Yaml Block to the Gatsby component using the Yaml ID
    - Allow Yaml Widgets to be full width
    - Can be used outside (full-width) or inside a section (page-container width)
- Added PageContainer component to handle the wrapper elements (e.g. `<div class="page-container">` and `<div class="site-content row">`)
- Added custom component blocks for International page (button section, stats section and media/text section)

### Changes to Existing Widgets
- Updated the use of the `<section>` element on the Media Text widget (have the media + text wrapped in a section rather than two sections, one containing media, one containing text, together wrapped in a div)
- Center-align Call to Action buttons and display in a row (in narrow mobile view, show as stacked)

### Styling Changes
- Each Widget now has its own set of wrapper divs (i.e. page-container, site-content), except Yaml Widgets (which need full width) and Modal Video widgets (which should not be constrained)
    - This increases the spacing around Section widgets
    - Removed extra vertical gap spacing showing up on Events widget (added surrounding gy-0 class)
- Made the CTA Heading a text-dark heading (h2 styled as an h3)
- Allowed font-size to be changed on Statistic.js title (used on Impact Report as one size and on International as another size)
- Added more specificity to card dt styles on basic pages (they were styling all dt elements rather than just card dt elements)
- Removed contentExists from Basic Page
- Added the (pre-existing) "content-area" wrapper class to make link hover/focus styles show up correctly (they were appearing with a secondary underline rather than the blue background hover that I believe was the original appearance on hover/focus)
- Added "main-column" id wrapper around basic page widgets (also affects how the hover/focus styles for links appear)

## Backend
[http://yamlblock-chug.pantheonsite.io](http://yamlblock-chug.pantheonsite.io)
- Added Yaml Block (for storing the Yaml ID and mapping)
- Added Yaml Widget paragraph for adding the Yaml block on a Drupal Basic Page.
- **NEW:** Enabled Paragraphs Type Permissions and restricted Yaml Widget to Administrators (Authors and editors can still move a placed Yaml widget up or down in the page order, but they cannot add a new Yaml widget to their page)
- Used Paragraph Stable display for Accordions (rather than Paragraph Legacy) to fix truncated Accordion Item title
- Moved Tab Title to top of display (above Tab Content)
- **NEW:** Added Modal Video to Basic page content type

----
# Test Plan

1. Go to [https://build-c0510911-c91b-4d59-b3ad-7120c6a2f1d0.gtsb.io/explore-u-of-g-international](https://build-c0510911-c91b-4d59-b3ad-7120c6a2f1d0.gtsb.io/explore-u-of-g-international). 
2. Go to [https://yamlblock-chug.pantheonsite.io/node/834/edit](https://yamlblock-chug.pantheonsite.io/node/834/edit) to view Drupal node
3. View examples of Yaml Blocks at [https://yamlblock-chug.pantheonsite.io/admin/structure/block/block-content](https://yamlblock-chug.pantheonsite.io/admin/structure/block/block-content)
4. The component will not render if:
    - People have a mistake in their Yaml mapping
    - People change the name of the Yaml ID and it's no longer found by Gatsby
(Although the surrounding wrapper div will render, but the null contents is still better than an error if the Yaml map is broken.)

# Caveats
- There are no revisions on Drupal 9 blocks. (At least not yet - D9 is working on it, but until it's available, no revisions.) This means if a block gets deleted, there's no backup. If users do NOT need to change the content, it would probably be better to store the content in Gatsby since that has revisions. If content needs to be changed frequently, we can go the route of allowing users to have access to the YAML mapping via Yaml blocks.

-----
# Creating a custom component in future...

## Step 1 - Create component under src/components/blocks/
- You can either source your Yaml data from the Gatsby side at src/data/block/
    - See Impact Report blocks at src/components/blocks/economic-impact for an example of these query types)
- OR you can source your data from the Drupal Yaml Block mapping field (see example below).

```
import React from "react"
import { StaticQuery, graphql } from "gatsby"

const yaml = require('js-yaml');

const render = ({ field_yaml_map, relationships }) => {
  let yamlMap;
  let yamlFiles = {};
  relationships.field_yaml_files.forEach(file => {
    yamlFiles[file.path.alias] = file.relationships.field_media_image.localFile;
  });

  try {
    yamlMap = yaml.load(field_yaml_map);
  } catch (e) {
    console.log(e);
    return null;
  }
    
  return (
    // Render component here
  )

}

// Add id of component to query and name component here
const query = graphql`
  query {
    blockContentYamlBlock(field_yaml_id: {glob: "id_of_my_yaml_block"}) {
      id
      field_yaml_id
      field_yaml_map
      relationships {
        field_yaml_files {
          id
          name
          relationships {
            field_media_image {
              localFile {
                childImageSharp {
                  gatsbyImageData(placeholder: BLURRED, layout: CONSTRAINED)
                }
              }
            }
          }
          path {
            alias
          }
        }
      }
    }
  }
`
// Add unique name of component here
export default function UniqueNameOfComponent() {
  return <StaticQuery query={query} render={({blockContentYamlBlock}) => render(blockContentYamlBlock)} />
}
```
## Step 2 - Map block to component in components/shared/yamlWidget.js
```
// @todo - add index of components in components/blocks and import all in one line
// until then, import each component manually below
import InternationalStatsGlobal from 'components/blocks/international/international-stats-global'
import InternationalExploreThingsToKnow from 'components/blocks/international/international-things-to-know'
import InternationalExploreButtons from 'components/blocks/international/international-explore-btns'
import UniqueNameOfComponent from 'components/blocks/international/id-of-my-yaml-block'

const YamlWidget = (props) => {
    let component = props.blockData.relationships.field_custom_block?.field_yaml_id;

    // add new custom components to conditional rendering below
    return ({
        'international_stats_global_impact': <InternationalStatsGlobal />,
        'international_explore_things_to_know': <InternationalExploreThingsToKnow />,
        'international_explore_btns': <InternationalExploreButtons />,
        'id_of_my_yaml_block': <UniqueNameOfComponent />,
    }[component] || null )
}
```

## Step 3 - Add block to Drupal backend
- Add Yaml ID
- Add your Yaml mapping (I typically type it up in a code editor and paste it in, simply because the tab key isn't available in the WYSIWYG)
- When referencing images in the Yaml mapping, use the URL alias of the image (you can find it when looking at the image in the Content / Media tab)
- Attach any images you are using (I've only added the ability to attach images, but in future, we'll be able to attach files if we update the schema)

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
For the backend, I would strongly recommend making the `Yaml Block` field mandatory. I also notice the `Section Column` field has the extra option `N/A` - the help text (currently blank) should be updated to explain what this means. Does it make the Yaml widget full-width?

image

**Comment by mmafe** [comment]
Good points! I had added the Section Column in case we needed to have something in one of the columns, but had not tested out N/A or To Be Discontinued. I'll run a build to see what it does.

**Comment by mmafe** [comment]
Added help text to the Section Column (basically if you want full width, don't put the Yaml widget in a Section. It seems to ignore the section column setting, so I've recommended N/A. If you do put it in a Section column, recommend using Primary or Secondary.)

Tested here by sticking the same Yaml Block in different sections: https://build-5fe12150-9371-47b3-9302-0fecc7270392.gtsb.io/test-yaml-blocks-in-sections

**Comment by tqureshi-uog** [comment]
If time permits, it might (as discussed previously over Teams) be worth checking to see if this module resolves the Block revision issue: https://www.drupal.org/project/block_content_revision_ui

**Comment by mmafe** [comment]
For next sprint, I'm also thinking I should turn on Paragraph Type Permissions and restrict the usage of the Yaml Block to administrators (at least for now).

**Comment by mmafe** [comment]
**NEW:** Enabled Paragraphs Type Permissions and restricted Yaml Widget to Administrators (Authors and editors can still move a placed Yaml widget up or down in the page order, but they cannot add a new Yaml widget to their page)

**Comment by mmafe** [comment]
Noticed a display issue on the program pages. Will fix.
image

**Comment by mmafe** [comment]
Seeing a horizontal scrollbar on my Explore International page with the Yaml blocks. Will fix. It's not showing on other pages, so I think it'll be specific to one of the Yaml blocks.

**Comment by mmafe** [comment]
The Gatsby Cloud PR build for this branch is getting a cache-related error. Rather than clearing the UG live cache, I've just set up my preview environment so it runs the yamlblock branch against the live site data.

You can view it here: https://preview-mmtest.gtsb.io/

**Review by snschau — APPROVED** [review]
All pages I have looked at have worked as I think they are expected to. I have not had time to build a test page from scratch - however, looking at the international page, things are working. I don't see any obvious reason not to go forward with this PR.

**Review by tqureshi-uog — CHANGES_REQUESTED** [review]
Could you make the Section Column field mandatory like it is for all other widgets, with the default selection "Primary"? That way, the "N/A" option will disappear.

**Comment by mmafe** [comment]
Updated Section Column to be mandatory and set default selection to Primary. Also merged in latest updates (Drupal core) from dev. New build at https://mmtest.gatsbyjs.io/explore-u-of-g-international

**Review by tqureshi-uog — APPROVED** [review]
Approved. We'll have to update user instructions on the Sharepoint site to let them know about the question mark icon to toggle widget help text

**Pull request merged**
