### PR TITLE
Add Accordion and Tabs widgets to Section

### PR DESCRIPTION
**Pull request by tqureshi-uog**
# Summary of changes
The basic page template for majors is supposed to match https://www.uoguelph.ca/dev/programs/environmental-management-major - this requires that the Tabs widget be made available to Sections. The Accordion widget is also being added for use in future layouts.

## Frontend
- Accordion widget added to `sectionWidgets.js`
- Tabs widget added to  `sectionWidgets.js`
- `field_section_column` added to GraphQL queries in `accordion.js` and `pageTabs.js`
- Schema updated in `gatsby-node.js`
- Packages upgrade to latest versions (incidental change)

## Backend
- Accordion and Tabs paragraph types made available to Section Widget
- Section Column field added to Accordion and Tabs paragraph types

# Test Plan

Drupal multidev: https://majors-chug.pantheonsite.io/
 
- Go to https://tqtest.gatsbyjs.io/majors-template
- Verify the overall layout is consistent with https://www.uoguelph.ca/dev/programs/environmental-management-major
- Go to https://tqtest.gatsbyjs.io/test-widgets
- Verify the Accordion and Tabs widgets work as expected

## Known issues
- The `Apply Now` button on https://tqtest.gatsbyjs.io/majors-template uses the button widget and, due to hard-coded classes, is narrower than the same button on https://www.uoguelph.ca/dev/programs/environmental-management-major - altering this behavior is beyond the scope of this pull request, but a workaround could involve using a general text widget in full html format instead (which in turn would permit adding a button with different classes).

### CODE REVIEW

**Comment by snschau** [comment]
everything looks good - just not sure why button.js is throwing up an error with uri (null value). in the one check.

**Comment by tqureshi-uog** [comment]
> everything looks good - just not sure why button.js is throwing up an error with uri (null value). in the one check.

I wondered about that as well. It appears to be a random timeout error on Gatsby Cloud unrelated to this PR. I figured out how to re-trigger the PR build and this time, it worked: https://www.gatsbyjs.com/dashboard/2e86c058-a370-4898-ae51-9698cd178e8d/sites/fc8e90a4-54ce-4012-a5fc-3302f05a3d6d/builds/a4dcec2b-cf9c-4992-b69d-56dc4c1d3efd/details

**Review by snschau — APPROVED** [review]

**Comment by abanuog** [comment]
Everything seems to be working as expected. The one thing I would suggest is put something in the Help text for the section columns, regarding this note:

"NOTE: the Gatsby component sectionWidget.js will only render tabs and accordions in the default Primary section. If Section Column is set to anything else, they will be ignored and not render."

**Comment by tqureshi-uog** [comment]
> Everything seems to be working as expected. The one thing I would suggest is put something in the Help text for the section columns, regarding this note:
> 
> "NOTE: the Gatsby component sectionWidget.js will only render tabs and accordions in the default Primary section. If Section Column is set to anything else, they will be ignored and not render."

There is help text to address this (in the Gin admin theme, help text doesn't display by default - you need to click the little question-mark icon):

image

image

**Review by abanuog — APPROVED** [review]

**Pull request merged**
