### PR TITLE
Inlineimage

### PR DESCRIPTION
**Pull request by snschau**
# Summary of changes
add function to enable inline images to the General Text Widget. (i.e. add the URLBASE (environment variable) to the sourse in Gatsby so that the images are displayed).

## Frontend
Created a function to modify the src for img and figure tags to add the URLBASE (environment variable) to the start of the src tag location. Also, to add spacing css based on left, right, centre or none. If the image had a caption and becomes a figure, there is different classes added. 

added "html-react-parser": "^1.4.12", - to package.jason to be able to parse html in react. 

## Backend
Multidev imce-image : https://imce-image2-chug.pantheonsite.io/

Added IMCE Module to drupal - configured it as below:
 - all users that have author and editor roles can access the inline-image folder (browse files, browse subfolders, create subfolder upload file) (not sure if they should be able to delete or resize images - maybe a "site" admin might have those - not sure.
 - Maximum file Size 20 mb
 - Maximum image dimensions 1920x1080

# Test Plan

https://gusinlineimage.gtsb.io/widget-options 
https://gusinlineimage.gatsbyjs.io/testing-inline-images
- have all the options that can be displayed for images and figures. 

Test adding a general text widget - check that IMCE is working for different users. 

Insert steps. Include URLs of Gatsby Cloud test site and Drupal multidev.

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
One issue I see as far as the backend goes is that content editors have no way to re-use existing images - they're constantly forced to upload which could result in large numbers of duplicate files (with no size restriction either, thus cluttering up the Drupal site and making builds even slower).

If this PR can wait till next week, I would strongly recommend creating a multidev (there are 3 free slots right now) and testing the Drupal 9 version of the IMCE module: https://www.drupal.org/project/imce (it shouldn't require changes to the Gatsby frontend code; all it does is allow content editors to browse the backend for existing images, thus making the process far more user-friendly)

**Comment by snschau** [comment]
> One issue I see as far as the backend goes is that content editors have no way to re-use existing images - they're constantly forced to upload which could result in large numbers of duplicate files (with no size restriction either, thus cluttering up the Drupal site and making builds even slower).
> 
> If this PR can wait till next week, I would strongly recommend creating a multidev (there are 3 free slots right now) and testing the Drupal 9 version of the IMCE module: https://www.drupal.org/project/imce (it shouldn't require changes to the Gatsby frontend code; all it does is allow content editors to browse the backend for existing images, thus making the process far more user-friendly)

Sounds good - I will look into it.

**Comment by mmafe** [comment]
I'm noticing that figure/figcaption images are not responsive. Also the first image in the Widget Options test page does not appear to be responsive. Can we add that?

**Comment by tqureshi-uog** [comment]
When I merged imce-image into my own tqtest multidev and then tried to import config, it wiped out the latest changes from master (Gin theme, Menu permissions, etc). Please update the imce-image multidev so it has the latest changes from master.

**Comment by snschau** [comment]
i have merged master for the mulidev

**Comment by tqureshi-uog** [comment]
> i have merged master for the mulidev

I'm still not seeing the Gin theme on https://imce-image-chug.pantheonsite.io/ - did you import config?

**Comment by snschau** [comment]
> 

Something went wrong - talked with Miranda - working on a fix

**Comment by snschau** [comment]
i have made a new mulidev - https://imce-image2-chug.pantheonsite.io/ - use that for testing

**Pull request closed without merging**
