### PR TITLE
Add 404 page to Content Hub

### PR DESCRIPTION
**Pull request by mmafe**
# Summary of changes
- Add 404 page to Content Hub
- Update footer so it sticks to the bottom of the page

## Frontend
- Add 404 page to Content Hub

## Backend
- none

# Test Plan

Go to /jfkdlsjkla and when Gatsby shows there's no such page, select "Preview custom 404 page" button to see the page.

### CODE REVIEW

**Comment by tqureshi-uog** [comment]
The only glitch I've found so far is with the `archival copy` link - if you go to https://ugconthub-404.gatsbyjs.io/cows and then click it, you'll be taken here: https://web.archive.org/web/20230000000000*/https://www.uoguelph.ca

If you do the same for https://www.uoguelph.ca/cows you'll be taken here: http://web.archive.org/web/20230000000000*/https://www.uoguelph.ca/cows

So for some reason, the code on the Gatsby version isn't grabbing the page name/slug (this could simply be a temporary glitch, so others should test as well).

**Comment by RazaMM** [comment]
> The only glitch I've found so far is with the `archival copy` link - if you go to https://ugconthub-404.gatsbyjs.io/cows and then click it, you'll be taken here: https://web.archive.org/web/20230000000000*/https://www.uoguelph.ca
> 
> If you do the same for https://www.uoguelph.ca/cows you'll be taken here: http://web.archive.org/web/20230000000000*/https://www.uoguelph.ca/cows
> 
> So for some reason, the code on the Gatsby version isn't grabbing the page name/slug (this could simply be a temporary glitch, so others should test as well).

I am seeing the same issue, which is weird because it works on doorknob but not here despite being the same code.

**Comment by mmafe** [comment]
@RazaMM  and @tqureshi-uog , are you still seeing the same issue with the latest update?

**Comment by mmafe** [comment]
Argh...I am still seeing it.

**Comment by tqureshi-uog** [comment]
I haven't tested locally, but I am still seeing it on the Gatsby builds.

**Review by RazaMM — DISMISSED** [review]

**Review by RazaMM — CHANGES_REQUESTED** [review]
Can we make it so the footer appears at the bottom like it does on doorknob?

Other than that everything looks good.

gus:
CleanShot 2023-10-16 at 15 41 06@2x

doorknob:
CleanShot 2023-10-16 at 15 41 29@2x

**Comment by mmafe** [comment]
@RazaMM Updated the footer so it sticks to the bottom

**Review by RazaMM — APPROVED** [review]

**Pull request merged**
