### PR TITLE
accordian Widget configuration

### PR DESCRIPTION
**Pull request by snschau**
SUMMARY:

This feature will add an accordion widget to the widget field. This will allow for the addition of accordion elements to be added to a page. Each accordion can have as many expanding points as needed.  

BACKEND (Drupal): https://accordion-chug.pantheonsite.io/
- Paragraph Accordion Section 
  - which only has one field that is a reference to the Accordion Block paragraph
- Paragraph Accordion Block
  - Two fields, both of which are formatted so that basic html can be used 
    -  Title
    -  Text
 
FRONTEND (Gatsby): gus/accordion branch
- gatsby-node.js - add paragraph__accordion_section to widgetParagraphUnion
- widget.js - add code to display paragraph 
- basic-page.js - added to query to include the accordion paragraphs from drupal

TESTING (Gatsby Cloud): 
https://www.gatsbyjs.com/dashboard/2e86c058-a370-4898-ae51-9698cd178e8d/sites/4d03c6f6-9271-4faf-8419-e36460e489d7/deploys
https://gusaccordion.gatsbyjs.io/

Existing page
- https://gusaccordion.gatsbyjs.io/masters-of-biomedical-sciences-mbs the accordions on that page are done by the widget.
New page
- Add new basic page and add an accordion widget with at least one accordion block. 
- trigger build on gatsby cloud and examine page to ensure the accordion widget is working.
- edit widget and add <strong> </strong> around the title field and re-trigger build to ensure the formatting works. 
- Add a second accordion to the page to ensure that multiple accordion widgets can work on one page.
-re-trigger build

### CODE REVIEW

**Comment by abanuog** [comment]
Not sure if this is exactly related to the changes you made, but halfway down the page, starting with:
Applied Toxicology Contact
Gordon M. Kirby, DVM, MSc, PhD

the page content layout looks off.

**Comment by abanuog** [comment]
https://build-e7a1ba8f-ca59-474b-989a-389ee322cda9.gtsb.io/test-for-accordions-pr

I added two separate acc blocks, the second has only one item (Another Block). If I click
to open that one, it also open the first item from the first block. Not sure it that's because
there's no other text/widget between the acc blocks?

**Comment by snschau** [comment]
> 

This is due to a cut and paste - just it is not related to the accordion.

**Comment by snschau** [comment]
> https://build-e7a1ba8f-ca59-474b-989a-389ee322cda9.gtsb.io/test-for-accordions-pr
> 
> I added two separate acc sections, the second has only one item (Another Block). If I click to open that one, it also open the first item from the first block. Not sure it that's because there's no other text/widget between the acc blocks?
> 
> UPDATE: I added a text widget between the two acc sections, and the same issue is happening.

I have fixed this

**Comment by abanuog** [comment]
ok, seems to be working now after the fix

**Comment by tqureshi-uog** [comment]
@snschau Build is still failing. See https://www.gatsbyjs.com/dashboard/2e86c058-a370-4898-ae51-9698cd178e8d/sites/fc8e90a4-54ce-4012-a5fc-3302f05a3d6d/builds/b7a6225d-2999-4794-9b20-9f6ab8710642/details#rawLogs - looks like further additions are needed for gatsby-node.js

**Comment by snschau** [comment]
Tanya and Joy - i have been trying to figure out what I have done wrong in the Schema - I can't seem to figure it out - it in gatsby-node.js currently the items are from line 1132 to 164 - it builds - but get an error when the page displays.  If you have time to look at it in early January - that would be great. I will be around on the 10th maybe we can have a look at it then.  Thanks. (Hope you had a good break).

Scott.

**Review by tqureshi-uog — APPROVED** [review]

**Pull request merged**
